<center> <h2>Ejercicio 04</h2> </center> 

De la siguiente Matriz

<img src="https://user-images.githubusercontent.com/19308295/115969506-dbbc4b00-a502-11eb-9c76-c9da265c5366.png"
    style="width:400px"></img>

* Luego invertir lo valores de 9 y 1 de la Matriz anterior

In [2]:
import numpy as np

In [13]:
a=np.array([(1,1,1,1,1),(1,0,0,0,1),(1,0,9,0,1),(1,0,0,0,1),(1,1,1,1,1)])
print(a)

b=9*a
b[2,2]=1
print(b)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[9 9 9 9 9]
 [9 0 0 0 9]
 [9 0 1 0 9]
 [9 0 0 0 9]
 [9 9 9 9 9]]
